language: bash

services:
  - docker

env:
  global:
    - DOCKER_NAMESPACE="kolla"
    - KOLLA_BASE_DISTRO="centos"
    - INSTALL_TYPE="source"
    - TAG="ussuri"
    - ALIYUN_REGISTRY="registry.cn-shenzhen.aliyuncs.com"
    - ALIYUN_NAMESPACE="kollaimage"

before_script:
  - echo "$ALI_PASSWORD" | docker login "$ALIYUN_REGISTRY" -u "$ALI_USERNAME" --password-stdin
  - bash get_kolla_images_list.sh
  - images=$(cat images.txt)
  - echo -e "All images is:\n$images"
  - count=$(echo "$images" |wc -l)
  - echo "Images count is $count"

jobs:
  include:
    - stage: test
      script: sh pull1.sh
    - script: sh pull2.sh
