language: bash

services:
  - docker

env:
  global:
    - IMAGEFILE=images
    - DOCKER_NAMESPACE="kolla"
    - KOLLA_BASE_DISTRO="centos"
    - INSTALL_TYPE="source"
    - TAG="ussuri"
    - ALI_REGISTRY="registry.cn-shenzhen.aliyuncs.com"
    - ALIYUN_NAMESPACE="kollaimage"

before_script:
  - echo "$ALI_PASSWORD" | docker login "$ALI_REGISTRY" -u "$ALI_USERNAME" --password-stdin
 
script:
  - git clone https://github.com/openstack/kolla.git
  - images=$(ls -l ./kolla/docker | grep "^d" | awk '{print $NF}')
  - echo "All images is: $images"
  - count=`cat $IMAGEFILE |wc -l`
  - echo "Images count is $count"
  - icount=1
  - |
    for image in $images
    do
      echo [$icount/$count]: $image
      docker pull $DOCKER_NAMESPACE/${KOLLA_BASE_DISTRO}-${INSTALL_TYPE}-$image:$TAG
      docker tag $DOCKER_NAMESPACE/${KOLLA_BASE_DISTRO}-${INSTALL_TYPE}-$image:$TAG $ALI_REGISTRY/$ALIYUN_NAMESPACE/${KOLLA_BASE_DISTRO}-${INSTALL_TYPE}-$image:$TAG
      docker push $ALI_REGISTRY/$ALIYUN_NAMESPACE/${KOLLA_BASE_DISTRO}-${INSTALL_TYPE}-$image:$TAG
      ((icount++))
    done
